apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
spec:
  selector:
    app: rest-api-service
  ports:
    - name: rest-api-tcp
      protocol: TCP
      port: 3000
      targetPort: rest-api-svc
  type: LoadBalancer
